### ISSUE TITLE
Fails to run due to TypeError in `graphql-codegen`

### ISSUE THREAD

**Issue by EvHaus** [webpro-nl/knip#658]
After running `knip` for the first time in my project, it fails with the following:

```
yarn run v1.22.19
$ knip
Analyzing workspace ....
file:///myproject/node_modules/knip/dist/plugins/graphql-codegen/index.js:27
        .flatMap(config => Object.values(config?.generates));
                                  ^

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at file:///myproject/node_modules/knip/dist/plugins/graphql-codegen/index.js:27:35
    at Array.flatMap (<anonymous>)
    at Object.resolveConfig (file:///myproject/node_modules/knip/dist/plugins/graphql-codegen/index.js:27:10)
    at WorkspaceWorker.findDependenciesByPlugins (file:///myproject/node_modules/knip/dist/WorkspaceWorker.js:214:83)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///myproject/node_modules/knip/dist/index.js:108:108)
    at async run (file:///myproject/node_modules/knip/dist/cli.js:23:73)
    at async file:///myproject/node_modules/knip/dist/cli.js:90:1

Node.js v20.12.0
```

I'm not using any custom configs. Just running `knip` fresh for the first time when this happens.

Running `knip --debug` also fails with the same error, but it shows that this happens immediately parsing my `codegen.ts` file. Perhaps something is wrong there?

```
[.] GraphQL Codegen config file paths (2)
[
  '/myproject/.graphqlrc.js',
  '/myproject/codegen.ts'
]
file:///myproject/node_modules/knip/dist/plugins/graphql-codegen/index.js:27
        .flatMap(config => Object.values(config?.generates));
                                  ^

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at file:///myproject/node_modules/knip/dist/plugins/graphql-codegen/index.js:27:35
    at Array.flatMap (<anonymous>)
    at Object.resolveConfig (file:///myproject/node_modules/knip/dist/plugins/graphql-codegen/index.js:27:10)
    at WorkspaceWorker.findDependenciesByPlugins (file:///myproject/node_modules/knip/dist/WorkspaceWorker.js:214:83)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///myproject/node_modules/knip/dist/index.js:108:108)
    at async run (file:///myproject/node_modules/knip/dist/cli.js:23:73)
    at async file:///myproject/node_modules/knip/dist/cli.js:90:1

Node.js v20.12.0
```

It's possible I'm doing wrong wrong as this is my first time trying out the tool, but after reading the docs and searching for issues, I wasn't able to find anyone running into anything like this.

I temporarily deleted my `.graphqlrc.js` and `codegen.ts` files to get `knip` to get past the error. So I'm guessing it doesn't like something about my `codegen.ts` file. It looks like this:

```
const sharedConfig = {
  preset: 'near-operation-file',
  presetConfig: {
    extension: '.generated.tsx',
    baseTypesPath: '~myproject-types/src/graphql',
    cwd: '/packages',
  },
  config: {
    withComponent: false,
    withHooks: true,
    withHOC: false,
    nonOptionalTypename: true,
    scalars: {
      BigInt: 'string',
      BigFloat: 'string',
      Cursor: 'string',
      ISO8601Date: 'string',
      ISO8601DateTime: 'string',
    },
  },
  plugins: ['typescript-operations', 'typescript-react-apollo'],
};

const config = {
  schema: 'packages/myproject-graphql/schema.gql',
  documents: [
    './packages/myproject-graphql/**/*.gql',
    './packages/myproject-core/**/*.gql',
    './packages/myproject-webapp/**/*.gql',
  ],
  generates: {
    'packages/myproject-types/src/graphql.ts': {
      config: {
        nonOptionalTypename: true,
        // Overwriting default 'any' type for the following scalars with string type zenhub/#26462
        scalars: {
          BigInt: 'string',
          BigFloat: 'string',
          Cursor: 'string',
          ISO8601Date: 'string',
          ISO8601DateTime: 'string',
        },
      },
      plugins: ['typescript'],
    },
    'myproject-core/': sharedConfig,
    'myproject-graphql/': sharedConfig,
  },
};

export default config;
```

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.17.1. See [Release 5.17.1](https://github.com/webpro-nl/knip/releases/tag/5.17.1) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._

**Comment by webpro** [comment]
Thanks for reporting this @EvHaus, nothing wrong with your config :)

**Comment by EvHaus** [comment]
Thanks for the super fast fix. Confirmed 5.17.1 resolves this.
