### ISSUE TITLE
`No "exports" main defined` error with `estree-walker` when using `mdx-js` plugin

### ISSUE THREAD

**Issue by EvHaus** [webpro-nl/knip#659]
My project has the `estree-walker` npm package somewhere in my `node_modules` folder and that seems like it causes `knip --debug` to crash with:

```
[packages/myproj-zhe-admin] Vite config file paths (1)
[ '/Users/myproject/packages/myproj-zhe-admin/vite.config.ts' ]
node:internal/modules/esm/resolve:304
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/myproject/node_modules/estree-walker/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
    at resolveExports (node:internal/modules/cjs/loader:590:36)
    at Module._findPath (node:internal/modules/cjs/loader:667:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:27)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at _resolve (/Users/myproject/node_modules/jiti/dist/jiti.js:1:251148)
    at jiti (/Users/myproject/node_modules/jiti/dist/jiti.js:1:253746)
    at /Users/myproject/node_modules/estree-util-build-jsx/lib/index.js:93:21
    at evalModule (/Users/myproject/node_modules/jiti/dist/jiti.js:1:256443) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.12.0
```

My `vite.config.ts` file looks like this:

```ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig(async () => {
  const mdx = await import('@mdx-js/rollup');

  return {
    plugins: [react(), mdx.default()],
    test: {
      coverage: {
        reporter: ['lcov', 'html'],
      },
      environment: 'happy-dom',
      setupFiles: ['./vitest.setup.ts'],
      poolOptions: {
        threads: {
          isolate: false,
        },
      },
    },
  };
});
```

I'm using:

- "@mdx-js/loader": "2.3.0"
- "@mdx-js/react": "2.3.0"
- "@mdx-js/rollup": "2.3.0"

I suspect this might be fixed with `mdx` version 3, but I haven't yet been able to upgrade to it due to other issues. I wonder if `knip` can be more tolerant of `estree-walker`'s package.json in this case. It looks like this:

```json
{
	"name": "estree-walker",
	"description": "Traverse an ESTree-compliant AST",
	"version": "3.0.3",
	"private": false,
	"author": "Rich Harris",
	"license": "MIT",
	"repository": {
		"type": "git",
		"url": "https://github.com/Rich-Harris/estree-walker"
	},
	"type": "module",
	"module": "./src/index.js",
	"exports": {
		"./package.json": "./package.json",
		".": {
			"types": "./types/index.d.ts",
			"import": "./src/index.js"
		}
	},
	"types": "types/index.d.ts",
	"scripts": {
		"prepublishOnly": "tsc && npm test",
		"test": "uvu test"
	},
	"dependencies": {
		"@types/estree": "^1.0.0"
	},
	"devDependencies": {
		"typescript": "^4.9.0",
		"uvu": "^0.5.1"
	},
	"files": [
		"src",
		"types",
		"README.md"
	]
}
```

**Comment by webpro** [comment]
Just a hunch: what if you use `knip-bun`? Requires to have Bun installed first.

If that doesn't help please create [a minimal reproduction](https://knip.dev/guides/troubleshooting#minimal-reproduction).

**Comment by EvHaus** [comment]
Yup. `knip-bun` works. That's good enough for me. ❤️  Bun

**Comment by webpro** [comment]
Nice! I'll add it to the page with known issues (https://knip.dev/reference/known-issues)

**Comment by webpro** [comment]
https://knip.dev/reference/known-issues/#config-files-using-esm-features
