### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" with self import

### ISSUE THREAD

**Issue by dnalborczyk** [webpro-nl/knip#663]
knip v5.17.3

```js
// index.js
import * as ns from './foo.js'

console.log(ns.foo)
console.log(ns.ns.foo)
console.log(ns.ns.ns.foo)
```

```js
// foo.js
import * as ns from './foo.js'

export { ns }

export const foo = class {}
```

```shell
➜ npx knip
Connecting the dots...
file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:3
    const getReExportingEntryFile = (importedModule, id, depth = 0, filePath) => {
                                    ^

RangeError: Maximum call stack size exceeded
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:3:37)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)
    at getReExportingEntryFile (file:///Users/daniel/.npm/_npx/5f5cbfb9ad5335bb/node_modules/knip/dist/util/get-reexporting-entry-file.js:53:34)

Node.js v20.14.0
```

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.18.0. See [Release 5.18.0](https://github.com/webpro-nl/knip/releases/tag/5.18.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
